apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontenddeploy
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers: 
      - name: frontend
        image: ninjaleo/reactlogin:latest
        terminationMessagePath: "/tmp/my-log"
        ports:
        - containerPort: 80
      nodeSelector:
        name: ninja
