apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontenddeploy
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers: 
      - name: frontend
        image: ninjaleo/reactlogin:latest
        terminationMessagePath: "/tmp/my-log"
      tolerations:
        - key: "name"
          operation: "Equal"
          value: "ninja"
          effect: "NoSchedule"
        ports:
        - containerPort: 80
