apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontenddeploy
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
        app: frontendapp
    spec:
      containers: 
      - name: frontend
        image: ninjaleo/reactlogin:latest
        ports:
        - containerPort: 80
   
