apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontenddeploy
spec: 
  replicas: 2
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers: 
      - name: frontend
        image: sureshtripini/quote-ui-prod:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
