apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 9376
      targetPort: 9376
      protocol: TCP
  selector:
    name: frontend
    app: frontendapp
  type: NodePort
