apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31008
      protocol: TCP
  selector:
    name: frontend
    app: frontendapp
  type: NodePort
