apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: frontend
    app: frontendapp
  type: LoadBalancer
